version: "3"
services:
  mysql:
    build: ./services/mysql
    container_name: local_mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql/:rw
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always

  nginx:
    build: ./services/nginx
    container_name: local_nginx
    depends_on:
      - php
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log/nginx:rw
      - ${NGINX_VHOST_PATH}:/etc/nginx/conf.d/:ro
      - ${NGINX_CONFIG_FILENAME}:/etc/nginx/nginx.conf:ro
    privileged: true
    restart: always

  php:
    build: ./services/php
    container_name: local_php
    expose:
      - "9000"
    links:
      - mysql
    volumes:
      - ${APPLICATION}:/var/www/html:rw
      - ${LOG_PATH}:/var/log:rw
      - ${PHP_INI_PATH}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_PATH}:/usr/local/etc/php-fpm.d/www.conf:rw
    privileged: true
    restart: always
